version: 0.2

phases:
  pre_build:
    commands:
      - dotnet clean
      - dotnet build -c Release
  build:
    commands:
      # dotnet test command builds the solution and runs a test host application for each test project in the solution.
      # You don't have to run dotnet restore because it's run implicitly by dotnet test
      - dotnet test -c Release --no-restore
